INSERT INTO ayush_systems (id, name, description, origin_text, color_hex, icon_emoji, plant_count) VALUES
(1, 'AYURVEDA', 'Classical Indian system focused on balance and prevention.', 'Rooted in Vedic knowledge and codified in classical samhitas.', '#2C5F3F', 'AY', 15),
(2, 'YOGA', 'Holistic mind-body system with herbal support for vitality.', 'Developed through yogic traditions and wellness lineages.', '#4A7BA7', 'YO', 5),
(3, 'UNANI', 'Greco-Arabic medicine adapted in South Asia.', 'Expanded through Persian and Arab medical scholarship in India.', '#8B5E3C', 'UN', 5),
(4, 'SIDDHA', 'Tamil traditional medical science with mineral and herbal depth.', 'Evolved from Siddhar traditions in South India.', '#6B3FA0', 'SI', 5),
(5, 'HOMEOPATHY', 'Minimum-dose therapeutic system with remedy provings.', 'Popularized globally and practiced widely in India.', '#3A7B7B', 'HO', 5);

INSERT INTO ailment_categories (id, name, slug, icon_emoji, body_part, description) VALUES
(1, 'Fever', 'fever', 'fe', 'HEAD', 'Elevated body temperature with systemic discomfort.'),
(2, 'Digestion', 'digestion', 'di', 'STOMACH', 'Bloating, weak digestion, and appetite imbalance.'),
(3, 'Immunity', 'immunity', 'im', 'CHEST', 'Immune resilience and recurrent infection prevention.'),
(4, 'Skin Care', 'skin-care', 'sk', 'SKIN', 'Inflammation, acne, and skin barrier concerns.'),
(5, 'Stress and Anxiety', 'stress-anxiety', 'sa', 'HEAD', 'Nervous system regulation and calm support.'),
(6, 'Diabetes Support', 'diabetes', 'db', 'LIVER', 'Metabolic and sugar regulation support.'),
(7, 'Joint Pain', 'joint-pain', 'jp', 'JOINTS', 'Inflammatory and stiffness-oriented support.'),
(8, 'Respiratory', 'respiratory', 'rs', 'CHEST', 'Cough, congestion, and breathing support.'),
(9, 'Better Sleep', 'better-sleep', 'sl', 'HEAD', 'Sleep quality and relaxation support.'),
(10, 'Hair Growth', 'hair-growth', 'hg', 'SKIN', 'Scalp nourishment and hair vitality support.'),
(11, 'Eye Care', 'eye-care', 'ec', 'EYES', 'Eye strain and visual comfort support.'),
(12, 'Memory and Focus', 'memory-focus', 'mf', 'HEAD', 'Cognitive support and concentration.'),
(13, 'Liver Support', 'liver-support', 'lv', 'LIVER', 'Hepatic protection and detox support.'),
(14, 'Kidney Support', 'kidney-support', 'kd', 'KIDNEYS', 'Urinary and renal wellbeing support.'),
(15, 'Heart Health', 'heart-health', 'hh', 'HEART', 'Cardiovascular support and circulation wellness.');

INSERT INTO garden_zones (id, zone_name, zone_key, description, ayush_system_id, svg_path_data, svg_cx, svg_cy, color_hex, icon_emoji) VALUES
(1, 'Healing Herbs Garden', 'healing-herbs', 'Core Ayurvedic herbs and daily-use leaves.', 1, 'M110,130 L410,130 L430,300 L90,300 Z', 260, 220, '#2C5F3F', 'ZH'),
(2, 'Sacred Grove', 'sacred-grove', 'Traditional sacred trees with ritual significance.', 1, 'M480,90 L760,110 L740,320 L470,300 Z', 620, 210, '#1A3A2A', 'ZG'),
(3, 'Aromatic Bliss', 'aromatic-bliss', 'Fragrant herbs supporting mind and prana.', 2, 'M820,130 L1080,130 L1110,290 L800,320 Z', 960, 220, '#4A7BA7', 'ZA'),
(4, 'Unani Medicinal Beds', 'unani-beds', 'Classical Unani materia medica selection.', 3, 'M120,360 L420,360 L400,560 L140,560 Z', 270, 460, '#8B5E3C', 'ZU'),
(5, 'Yoga and Pranayama', 'yoga-pranayama', 'Calming botanicals for yogic routines.', 2, 'M470,360 L730,360 L760,560 L450,560 Z', 600, 460, '#4A7BA7', 'ZY'),
(6, 'Siddha Alchemy', 'siddha-alchemy', 'Siddha-oriented plants used in southern traditions.', 4, 'M790,360 L1090,360 L1090,560 L790,560 Z', 940, 460, '#6B3FA0', 'ZS'),
(7, 'Homeopathy Meadow', 'homeopathy-meadow', 'Plants linked with common homeopathic remedies.', 5, 'M220,620 L520,620 L500,820 L220,820 Z', 360, 720, '#3A7B7B', 'ZM'),
(8, 'Cultivation Nursery', 'cultivation-nursery', 'Hands-on growing and propagation hub.', NULL, 'M610,620 L990,620 L990,820 L610,820 Z', 800, 720, '#7BAF7B', 'ZN');

INSERT INTO plants (
  id, common_name, scientific_name, sanskrit_name, local_names, plant_family, plant_type, native_region, native_lat, native_lng,
  description, morphology, identifying_features, main_image_url, gallery_images, parts_used, rasa, virya, vipaka,
  body_parts, harvest_months, bloom_months, active_compounds, precautions, contraindications,
  is_featured, is_active, view_count, bookmark_count
) VALUES
(1, 'Tulsi', 'Ocimum tenuiflorum', 'Tulasi', '{"hindi":"tulsi","tamil":"thulasi","telugu":"tulasi"}', 'Lamiaceae', 'HERB', 'Pan-India', 23.593700, 80.962900, 'Sacred aromatic herb used for immunity and respiratory care.', 'Branched aromatic herb with opposite leaves and purple inflorescences.', 'Clove-like aroma and serrated oval leaves.', '/images/plants/tulsi.jpg', '["/images/plants/tulsi-1.jpg","/images/plants/tulsi-2.jpg"]', 'Leaf, seed', 'Pungent, Bitter', 'Hot', 'Pungent', '["HEAD","CHEST","THROAT"]', '[1,2,3,10,11,12]', '[8,9,10]', 'Eugenol, ursolic acid, rosmarinic acid', 'Avoid excess in pregnancy without clinician guidance.', 'May interact with blood-thinning medication.', TRUE, TRUE, 320, 120),
(2, 'Ashwagandha', 'Withania somnifera', 'Ashvagandha', '{"hindi":"ashwagandha","tamil":"amukkara"}', 'Solanaceae', 'SHRUB', 'North and Central India', 26.912400, 75.787300, 'Adaptogenic root used for stress, stamina, and sleep.', 'Small shrub with ovate leaves and orange-red berries.', 'Tomentose leaves and papery calyx around berry.', '/images/plants/ashwagandha.jpg', '["/images/plants/ashwagandha-1.jpg"]', 'Root', 'Bitter, Astringent', 'Hot', 'Sweet', '["HEAD","JOINTS"]', '[1,2,3,11,12]', '[10,11]', 'Withanolides, alkaloids', 'Use cautiously with sedative medications.', 'Avoid unsupervised use in hyperthyroid patients.', TRUE, TRUE, 280, 98),
(3, 'Turmeric', 'Curcuma longa', 'Haridra', '{"hindi":"haldi","tamil":"manjal"}', 'Zingiberaceae', 'HERB', 'South India', 10.850500, 76.271100, 'Golden rhizome used for inflammation and skin health.', 'Rhizomatous perennial with broad leaves and cone-like inflorescence.', 'Bright yellow-orange rhizome interior.', '/images/plants/turmeric.jpg', '["/images/plants/turmeric-1.jpg"]', 'Rhizome', 'Bitter, Pungent', 'Hot', 'Pungent', '["SKIN","JOINTS","LIVER"]', '[1,2,3,12]', '[7,8,9]', 'Curcumin, turmerones', 'High doses may irritate stomach in sensitive users.', 'Caution with anticoagulant therapy.', TRUE, TRUE, 300, 112),
(4, 'Neem', 'Azadirachta indica', 'Nimba', '{"hindi":"neem","tamil":"veppam"}', 'Meliaceae', 'TREE', 'Pan-India', 20.593700, 78.962900, 'Classic bitter tree used in skin and metabolic protocols.', 'Evergreen tree with pinnate leaves and drupaceous fruit.', 'Intensely bitter leaves and serrate leaflets.', '/images/plants/neem.jpg', '["/images/plants/neem-1.jpg"]', 'Leaf, bark, seed', 'Bitter', 'Cold', 'Pungent', '["SKIN","LIVER"]', '[2,3,4,5]', '[3,4,5]', 'Nimbin, azadirachtin', 'Avoid high internal doses in children.', 'Pregnancy contraindication for concentrated extracts.', TRUE, TRUE, 255, 103),
(5, 'Brahmi', 'Bacopa monnieri', 'Brahmi', '{"hindi":"brahmi","tamil":"neerbrahmi"}', 'Plantaginaceae', 'HERB', 'Wetlands across India', 11.016800, 76.955800, 'Nootropic herb for memory and calm cognition.', 'Creeping succulent herb with small white flowers.', 'Fleshy leaves and prostrate growth near water.', '/images/plants/brahmi.jpg', '["/images/plants/brahmi-1.jpg"]', 'Whole plant', 'Bitter', 'Cold', 'Sweet', '["HEAD"]', '[1,2,3,9,10,11,12]', '[6,7,8]', 'Bacosides', 'May cause mild GI discomfort in high doses.', 'Caution with thyroid medications.', TRUE, TRUE, 240, 95),
(6, 'Amla', 'Phyllanthus emblica', 'Amalaki', '{"hindi":"amla","tamil":"nellikkai"}', 'Phyllanthaceae', 'TREE', 'Pan-India', 22.973400, 78.656900, 'Vitamin C rich fruit for rejuvenation and immunity.', 'Medium deciduous tree with feathery branchlets.', 'Pale green sour fruits with 6 vertical furrows.', '/images/plants/amla.jpg', '["/images/plants/amla-1.jpg"]', 'Fruit', 'Sour, Astringent', 'Cooling', 'Sweet', '["CHEST","SKIN","HEAD"]', '[11,12,1,2]', '[3,4]', 'Ascorbic acid, emblicanin', 'Acidic preparations may irritate reflux-sensitive users.', 'Monitor sugar in sweetened formulations.', TRUE, TRUE, 210, 88),
(7, 'Shatavari', 'Asparagus racemosus', 'Shatavari', '{"hindi":"shatavari","tamil":"thanneer vittan"}', 'Asparagaceae', 'CLIMBER', 'Himalayan foothills and plains', 30.316500, 78.032200, 'Cooling tonic root used in women wellness and vitality.', 'Climbing plant with needle-like cladodes and tuberous roots.', 'Root fascicles and white fragrant flowers.', '/images/plants/shatavari.jpg', '["/images/plants/shatavari-1.jpg"]', 'Root', 'Sweet, Bitter', 'Cold', 'Sweet', '["LIVER","KIDNEYS"]', '[10,11,12,1]', '[7,8]', 'Saponins, shatavarins', 'Use under guidance in hormone-sensitive conditions.', 'Potential interaction with diuretics.', FALSE, TRUE, 160, 70),
(8, 'Giloy', 'Tinospora cordifolia', 'Guduchi', '{"hindi":"giloy","tamil":"seenthil"}', 'Menispermaceae', 'CLIMBER', 'Pan-India', 24.879999, 74.629997, 'Stem-based immunomodulator used for fevers and resilience.', 'Deciduous climber with heart-shaped leaves.', 'Warty stems and cordate leaves.', '/images/plants/giloy.jpg', '["/images/plants/giloy-1.jpg"]', 'Stem', 'Bitter', 'Hot', 'Sweet', '["CHEST","LIVER"]', '[1,2,3,8,9,10,11,12]', '[7,8]', 'Tinosporin, alkaloids', 'Use cautiously with autoimmune conditions.', 'May lower blood sugar; monitor with antidiabetics.', TRUE, TRUE, 230, 91),
(9, 'Moringa', 'Moringa oleifera', 'Shigru', '{"hindi":"sahjan","tamil":"murungai"}', 'Moringaceae', 'TREE', 'Dry tropical India', 17.385000, 78.486700, 'Nutrient dense tree used for strength and micronutrients.', 'Fast-growing tree with tripinnate leaves and long pods.', 'Drumstick pods and small leaflets.', '/images/plants/moringa.jpg', '["/images/plants/moringa-1.jpg"]', 'Leaf, pod, seed', 'Pungent, Bitter', 'Hot', 'Pungent', '["SKIN","LIVER","JOINTS"]', '[1,2,3,4,5,6,7,8,9,10,11,12]', '[2,3,4]', 'Quercetin, chlorogenic acid', 'High intake may cause GI upset.', 'Avoid root bark extracts during pregnancy.', FALSE, TRUE, 190, 74),
(10, 'Manjistha', 'Rubia cordifolia', 'Manjistha', '{"hindi":"manjistha","tamil":"manjetti"}', 'Rubiaceae', 'CLIMBER', 'Himalayan and peninsular India', 31.104800, 77.173400, 'Blood-purifying herb traditionally used for skin and circulation.', 'Perennial climber with rough stems and red roots.', 'Red dye yielding roots.', '/images/plants/manjistha.jpg', '["/images/plants/manjistha-1.jpg"]', 'Root', 'Bitter, Astringent', 'Hot', 'Pungent', '["SKIN","LIVER","HEART"]', '[10,11,12,1]', '[6,7]', 'Anthraquinones, mollugin', 'Avoid unsupervised use in pregnancy.', 'May interact with anticoagulants.', FALSE, TRUE, 120, 58),
(11, 'Haritaki', 'Terminalia chebula', 'Haritaki', '{"hindi":"harad","tamil":"kadukkai"}', 'Combretaceae', 'TREE', 'Sub-Himalayan and deciduous forests', 25.317600, 82.973900, 'Triphala component used for digestion and detox support.', 'Large deciduous tree with ribbed fruits.', 'Ellipsoid yellow-green fruits with ridges.', '/images/plants/haritaki.jpg', '["/images/plants/haritaki-1.jpg"]', 'Fruit', 'Astringent, Bitter', 'Hot', 'Sweet', '["STOMACH","LIVER"]', '[11,12,1,2,3]', '[4,5]', 'Chebulinic acid, tannins', 'Excess may cause loose stools.', 'Avoid dehydration-prone usage patterns.', FALSE, TRUE, 110, 49),
(12, 'Mulethi', 'Glycyrrhiza glabra', 'Yashtimadhu', '{"hindi":"mulethi","tamil":"athimadhuram"}', 'Fabaceae', 'HERB', 'Cultivated in North India', 28.613900, 77.209000, 'Soothing root for throat and respiratory comfort.', 'Perennial herb with pinnate leaves and lilac flowers.', 'Sweet root taste.', '/images/plants/mulethi.jpg', '["/images/plants/mulethi-1.jpg"]', 'Root', 'Sweet', 'Cold', 'Sweet', '["THROAT","CHEST"]', '[10,11,12,1,2]', '[5,6]', 'Glycyrrhizin', 'Long-term excess may elevate blood pressure.', 'Avoid with severe hypertension unless advised.', FALSE, TRUE, 105, 46),
(13, 'Gotu Kola', 'Centella asiatica', 'Mandukaparni', '{"hindi":"brahmi booti","tamil":"vallarai"}', 'Apiaceae', 'HERB', 'Moist tropical India', 12.971600, 77.594600, 'Cognitive and skin restorative creeping herb.', 'Small creeping herb with fan-shaped leaves.', 'Reniform leaves on long petioles.', '/images/plants/gotu-kola.jpg', '["/images/plants/gotu-kola-1.jpg"]', 'Whole plant', 'Bitter', 'Cold', 'Sweet', '["HEAD","SKIN"]', '[1,2,3,8,9,10,11,12]', '[6,7,8,9]', 'Asiaticoside, madecassoside', 'May cause drowsiness in some users.', 'Use caution with sedative drugs.', FALSE, TRUE, 132, 51),
(14, 'Punarnava', 'Boerhavia diffusa', 'Punarnava', '{"hindi":"punarnava","tamil":"mookkirattai"}', 'Nyctaginaceae', 'HERB', 'Pan-India', 26.449900, 80.331900, 'Renal and edema support herb in classic formulations.', 'Spreading perennial with fleshy roots.', 'Reddish stems and tiny pink flowers.', '/images/plants/punarnava.jpg', '["/images/plants/punarnava-1.jpg"]', 'Root, whole plant', 'Bitter, Astringent', 'Hot', 'Pungent', '["KIDNEYS","LIVER"]', '[7,8,9,10,11,12]', '[5,6,7,8]', 'Boeravinones', 'Monitor fluid balance in diuretic users.', 'Use supervised in renal compromise.', FALSE, TRUE, 98, 42),
(15, 'Vidanga', 'Embelia ribes', 'Vidanga', '{"hindi":"vidanga","tamil":"vayvilangam"}', 'Primulaceae', 'CLIMBER', 'Western Ghats and central belts', 15.299300, 74.124000, 'Traditional herb for gut cleansing and metabolic support.', 'Woody climber with small black berries.', 'Pepper-like berries and slender twigs.', '/images/plants/vidanga.jpg', '["/images/plants/vidanga-1.jpg"]', 'Fruit', 'Pungent, Bitter', 'Hot', 'Pungent', '["STOMACH","LIVER"]', '[11,12,1,2]', '[4,5]', 'Embelin', 'Use with professional guidance for prolonged dosing.', 'Avoid in pregnancy unless advised.', FALSE, TRUE, 70, 30),
(16, 'Ajwain', 'Trachyspermum ammi', 'Yavani', '{"hindi":"ajwain","tamil":"omam"}', 'Apiaceae', 'HERB', 'Northwest India', 28.704100, 77.102500, 'Aromatic seed used for digestion and colic relief.', 'Annual herb with umbels and ridged fruits.', 'Strong thymol aroma from seeds.', '/images/plants/ajwain.jpg', '["/images/plants/ajwain-1.jpg"]', 'Seed', 'Pungent', 'Hot', 'Pungent', '["STOMACH","THROAT"]', '[2,3,4]', '[1,2]', 'Thymol', 'Avoid excessive use in gastritis.', 'Pregnancy caution for concentrated oils.', FALSE, TRUE, 75, 29),
(17, 'Kalonji', 'Nigella sativa', 'Upakuncika', '{"hindi":"kalonji","tamil":"karunjeeragam"}', 'Ranunculaceae', 'HERB', 'Cultivated in North India', 26.846700, 80.946200, 'Seed spice used in Unani for immunity and metabolism.', 'Erect annual with pale blue flowers and black seeds.', 'Triangular black seeds with aromatic bitterness.', '/images/plants/kalonji.jpg', '["/images/plants/kalonji-1.jpg"]', 'Seed', 'Bitter, Pungent', 'Hot', 'Pungent', '["CHEST","LIVER"]', '[2,3,4]', '[2,3]', 'Thymoquinone', 'May lower blood sugar.', 'Caution with antihypertensive medication.', FALSE, TRUE, 82, 34),
(18, 'Arjun', 'Terminalia arjuna', 'Arjuna', '{"hindi":"arjun","tamil":"marudha maram"}', 'Combretaceae', 'TREE', 'Riverine India', 22.572600, 88.363900, 'Bark tonic for cardiovascular support.', 'Large tree with smooth pinkish-grey bark.', 'Characteristic exfoliating bark and buttressed trunk.', '/images/plants/arjun.jpg', '["/images/plants/arjun-1.jpg"]', 'Bark', 'Astringent, Bitter', 'Cold', 'Pungent', '["HEART"]', '[10,11,12,1,2]', '[4,5]', 'Arjunolic acid, tannins', 'Use monitored with cardiac medication.', 'Do not replace prescribed cardiac therapy.', FALSE, TRUE, 150, 63),
(19, 'Senna', 'Senna alexandrina', 'Svarnapatri', '{"hindi":"sonamukhi","tamil":"nilavarai"}', 'Fabaceae', 'SHRUB', 'Dry regions', 23.022500, 72.571400, 'Leaf and pod laxative herb with short-term bowel use.', 'Small shrub with pinnate leaves and yellow flowers.', 'Characteristic sickle pods.', '/images/plants/senna.jpg', '["/images/plants/senna-1.jpg"]', 'Leaf, pod', 'Bitter', 'Hot', 'Pungent', '["STOMACH"]', '[11,12,1,2,3]', '[6,7]', 'Sennosides', 'Not for long-term unsupervised use.', 'Contraindicated in bowel obstruction.', FALSE, TRUE, 60, 26),
(20, 'Atees', 'Aconitum heterophyllum', 'Ativisha', '{"hindi":"atees","tamil":"atividayam"}', 'Ranunculaceae', 'HERB', 'Western Himalaya', 32.239600, 77.188700, 'High-altitude medicinal root used traditionally for pediatric digestive care.', 'Erect herb with palmate leaves.', 'Distinct tuberous roots from alpine habitat.', '/images/plants/atees.jpg', '["/images/plants/atees-1.jpg"]', 'Root', 'Bitter', 'Cold', 'Pungent', '["STOMACH","CHEST"]', '[9,10,11]', '[7,8]', 'Atisine alkaloids', 'Only purified and authenticated material should be used.', 'Potential toxicity with adulterants.', FALSE, TRUE, 40, 15),
(21, 'Nilavembu', 'Andrographis paniculata', 'Kalmegha', '{"hindi":"kalmegh","tamil":"nilavembu"}', 'Acanthaceae', 'HERB', 'South India', 13.082700, 80.270700, 'Extremely bitter herb used in fever support protocols.', 'Erect annual with lanceolate leaves and tiny white flowers.', 'Strong bitter taste and square stems.', '/images/plants/nilavembu.jpg', '["/images/plants/nilavembu-1.jpg"]', 'Leaf, whole plant', 'Bitter', 'Cold', 'Pungent', '["HEAD","CHEST","LIVER"]', '[8,9,10,11]', '[8,9]', 'Andrographolide', 'Can reduce appetite in sensitive users.', 'Monitor with immunomodulating therapy.', FALSE, TRUE, 120, 55),
(22, 'Keezhanelli', 'Phyllanthus amarus', 'Bhumyamalaki', '{"hindi":"bhui amla","tamil":"keezhanelli"}', 'Phyllanthaceae', 'HERB', 'South and coastal India', 9.931200, 76.267300, 'Traditional liver-support herb in Siddha and Ayurveda.', 'Small erect herb with tiny leaves arranged on branchlets.', 'Miniature seed capsules under branches.', '/images/plants/keezhanelli.jpg', '["/images/plants/keezhanelli-1.jpg"]', 'Whole plant', 'Bitter, Astringent', 'Cold', 'Sweet', '["LIVER","KIDNEYS"]', '[1,2,3,4,5,6,7,8,9,10,11,12]', '[6,7,8]', 'Phyllanthin, hypophyllanthin', 'Use carefully in low blood sugar states.', 'Monitor with diabetic medications.', FALSE, TRUE, 101, 41),
(23, 'Thoothuvalai', 'Solanum trilobatum', 'Alarka', '{"hindi":"alarka","tamil":"thoothuvalai"}', 'Solanaceae', 'CLIMBER', 'Tamil Nadu belts', 11.127100, 78.656900, 'Siddha respiratory support herb for chronic cough patterns.', 'Spiny climber with lobed leaves and purple flowers.', 'Small prickles on leaves and stems.', '/images/plants/thoothuvalai.jpg', '["/images/plants/thoothuvalai-1.jpg"]', 'Leaf', 'Bitter, Pungent', 'Hot', 'Pungent', '["CHEST","THROAT"]', '[1,2,3,11,12]', '[7,8,9]', 'Solasodine', 'Spines require careful handling during preparation.', 'Avoid high use in gastric irritation.', FALSE, TRUE, 78, 33),
(24, 'Kokilaksha', 'Hygrophila auriculata', 'Ikshura', '{"hindi":"talmakhana","tamil":"kokilaksha"}', 'Acanthaceae', 'HERB', 'Marshy India', 18.520400, 73.856700, 'Urinary tract and kidney support plant.', 'Marsh herb with spiny bracts and purple flowers.', 'Aquatic habitat and whorled leaves.', '/images/plants/kokilaksha.jpg', '["/images/plants/kokilaksha-1.jpg"]', 'Seed, root', 'Sweet, Bitter', 'Cold', 'Sweet', '["KIDNEYS"]', '[9,10,11,12,1,2]', '[8,9,10]', 'Lupeol, flavonoids', 'Use with hydration and supervision.', 'Caution in severe renal disease.', FALSE, TRUE, 62, 24),
(25, 'Vembu Siddha', 'Azadirachta indica var. siddha', 'Vembu', '{"hindi":"neem siddha","tamil":"vembu"}', 'Meliaceae', 'TREE', 'Tamil regions', 11.664300, 78.146000, 'Siddha-context neem variant used for skin and metabolic balance.', 'Evergreen bitter tree.', 'Deeply serrated leaflets and bitter profile.', '/images/plants/vembu.jpg', '["/images/plants/vembu-1.jpg"]', 'Leaf, bark', 'Bitter', 'Cold', 'Pungent', '["SKIN","LIVER"]', '[2,3,4,5]', '[3,4,5]', 'Azadirachtin, limonoids', 'Avoid concentrated oil ingestion.', 'Contraindicated in pregnancy for internal concentrates.', FALSE, TRUE, 55, 20),
(26, 'Arnica Montana', 'Arnica montana', 'Arnica', '{"hindi":"arnica","tamil":"arnica"}', 'Asteraceae', 'HERB', 'Cultivated highland plots', 30.733300, 76.779400, 'Homeopathic source plant associated with trauma support.', 'Perennial herb with yellow daisy-like flowers.', 'Opposite basal leaves and bright capitula.', '/images/plants/arnica.jpg', '["/images/plants/arnica-1.jpg"]', 'Flower', 'Bitter', 'Hot', 'Pungent', '["JOINTS","SKIN"]', '[6,7,8]', '[6,7]', 'Helenalin', 'Crude internal use is not advised.', 'Use only in proper homeopathic preparations.', FALSE, TRUE, 48, 22),
(27, 'Belladonna', 'Atropa belladonna', 'Belladonna', '{"hindi":"belladonna","tamil":"belladonna"}', 'Solanaceae', 'HERB', 'Cultivated temperate gardens', 32.726600, 74.857000, 'Homeopathic source used in feverish acute symptom pictures.', 'Perennial herb with bell-shaped purple flowers.', 'Glossy black berries on mature plants.', '/images/plants/belladonna.jpg', '["/images/plants/belladonna-1.jpg"]', 'Leaf, root', 'Bitter', 'Hot', 'Pungent', '["HEAD","THROAT"]', '[7,8,9]', '[6,7]', 'Atropine alkaloids', 'Raw plant is toxic and should never be self-used.', 'Only regulated homeopathic preparations are acceptable.', FALSE, TRUE, 45, 18),
(28, 'Calendula', 'Calendula officinalis', 'Calendula', '{"hindi":"genda","tamil":"saamanthi"}', 'Asteraceae', 'HERB', 'Cultivated across India', 28.535500, 77.391000, 'Skin-supportive flower used in topical homeopathic products.', 'Annual herb with bright orange composite flowers.', 'Sticky leaves and resinous aroma.', '/images/plants/calendula.jpg', '["/images/plants/calendula-1.jpg"]', 'Flower', 'Bitter', 'Cooling', 'Pungent', '["SKIN"]', '[10,11,12,1,2,3]', '[11,12,1,2]', 'Flavonoids, triterpenes', 'Topical sensitivity testing is advised.', 'Avoid in known Asteraceae allergy.', FALSE, TRUE, 67, 28),
(29, 'Hypericum', 'Hypericum perforatum', 'Hypericum', '{"hindi":"hypericum","tamil":"hypericum"}', 'Hypericaceae', 'HERB', 'Temperate cultivated beds', 34.083700, 74.797300, 'Nerve support plant linked with homeopathic preparations.', 'Erect herb with yellow flowers and translucent leaf dots.', 'Perforated leaves under light.', '/images/plants/hypericum.jpg', '["/images/plants/hypericum-1.jpg"]', 'Flowering tops', 'Bitter', 'Hot', 'Pungent', '["HEAD","JOINTS"]', '[6,7,8]', '[6,7]', 'Hypericin, hyperforin', 'Photosensitivity risk in crude extract forms.', 'Drug interaction potential with antidepressants.', FALSE, TRUE, 42, 16),
(30, 'Pulsatilla', 'Pulsatilla nigricans', 'Pulsatilla', '{"hindi":"pulsatilla","tamil":"pulsatilla"}', 'Ranunculaceae', 'HERB', 'Cultivated cool gardens', 31.326000, 75.576200, 'Homeopathic source associated with mood and hormonal symptom sets.', 'Silky-haired perennial with nodding flowers.', 'Hairy stems and feathery seed heads.', '/images/plants/pulsatilla.jpg', '["/images/plants/pulsatilla-1.jpg"]', 'Whole plant', 'Bitter', 'Cold', 'Pungent', '["HEAD"]', '[5,6,7]', '[4,5,6]', 'Protoanemonin derivatives', 'Crude plant can irritate skin and mucosa.', 'Use only regulated preparations.', FALSE, TRUE, 39, 14),
(31, 'Shankhpushpi', 'Convolvulus pluricaulis', 'Shankhapushpi', '{"hindi":"shankhpushpi","tamil":"sankupushpam"}', 'Convolvulaceae', 'HERB', 'Dry plains of India', 23.259900, 77.412600, 'Medhya herb for focus and calm in yogic routines.', 'Prostrate herb with small blue-white flowers.', 'Conch-shaped flower form in folk naming.', '/images/plants/shankhpushpi.jpg', '["/images/plants/shankhpushpi-1.jpg"]', 'Whole plant', 'Bitter, Sweet', 'Cooling', 'Sweet', '["HEAD"]', '[1,2,3,9,10,11,12]', '[7,8,9]', 'Alkaloids, flavonoids', 'May cause mild drowsiness.', 'Caution with sedatives.', TRUE, TRUE, 155, 66),
(32, 'Vacha', 'Acorus calamus', 'Vacha', '{"hindi":"bach","tamil":"vasambu"}', 'Acoraceae', 'HERB', 'Wetlands and marshes', 26.144500, 91.736200, 'Aromatic rhizome used for speech and cognitive support traditions.', 'Marsh perennial with sword-like leaves.', 'Strongly aromatic rhizome.', '/images/plants/vacha.jpg', '["/images/plants/vacha-1.jpg"]', 'Rhizome', 'Pungent, Bitter', 'Hot', 'Pungent', '["HEAD","THROAT"]', '[10,11,12,1,2]', '[5,6]', 'Beta-asarone, eugenol traces', 'Use purified material and professional dosing.', 'Avoid in pregnancy and seizure disorders.', FALSE, TRUE, 88, 37),
(33, 'Jatamansi', 'Nardostachys jatamansi', 'Jatamansi', '{"hindi":"jatamansi","tamil":"jatamansi"}', 'Caprifoliaceae', 'HERB', 'Himalayan alpine zones', 30.316500, 78.032200, 'Aromatic root for deep calm and sleep support.', 'Perennial alpine herb with pink flowers.', 'Rhizome with musky fragrance.', '/images/plants/jatamansi.jpg', '["/images/plants/jatamansi-1.jpg"]', 'Rhizome, root', 'Bitter, Astringent', 'Cooling', 'Sweet', '["HEAD"]', '[9,10,11]', '[7,8]', 'Jatamansone, sesquiterpenes', 'May increase sedation with CNS depressants.', 'Use carefully in low blood pressure.', FALSE, TRUE, 92, 39),
(34, 'Kapikacchu', 'Mucuna pruriens', 'Kapikacchu', '{"hindi":"kaunch","tamil":"poonaikali"}', 'Fabaceae', 'CLIMBER', 'Tropical India', 19.076000, 72.877700, 'Bean used for neuromuscular and vitality support.', 'Twining climber with pods covered in irritant hairs.', 'Velvet bean pods with itchy trichomes.', '/images/plants/kapikacchu.jpg', '["/images/plants/kapikacchu-1.jpg"]', 'Seed', 'Sweet, Bitter', 'Hot', 'Sweet', '["HEAD","JOINTS"]', '[11,12,1,2,3]', '[8,9]', 'L-DOPA, alkaloids', 'Processing required before use; avoid raw pod contact.', 'Caution with dopaminergic medications.', FALSE, TRUE, 84, 35),
(35, 'Bhringraj', 'Eclipta prostrata', 'Bhringaraja', '{"hindi":"bhringraj","tamil":"karisalankanni"}', 'Asteraceae', 'HERB', 'Moist tracts across India', 12.295800, 76.639400, 'Classic herb for hair, liver, and restorative support.', 'Small branching herb with white flower heads.', 'Opposite leaves and tiny white capitula.', '/images/plants/bhringraj.jpg', '["/images/plants/bhringraj-1.jpg"]', 'Whole plant', 'Bitter, Pungent', 'Hot', 'Pungent', '["SKIN","LIVER","HEAD"]', '[1,2,3,4,5,6,7,8,9,10,11,12]', '[6,7,8,9]', 'Wedelolactone, ecliptine', 'Internal use should be guided in liver disease.', 'May interact with hepatically metabolized drugs.', TRUE, TRUE, 170, 72);

INSERT INTO plant_ayush_systems (plant_id, system_id, system_specific_name, system_specific_uses, classical_text_ref, mizaj, siddha_name, tincture_details) VALUES
(1,1,'Tulasi','Respiratory, immunity, adaptation','Charaka Samhita references',NULL,NULL,NULL),
(2,1,'Ashvagandha','Strength and stress resilience','Bhavaprakasha',NULL,NULL,NULL),
(3,1,'Haridra','Inflammation and skin','Sushruta mention',NULL,NULL,NULL),
(4,1,'Nimba','Skin and purification','Nighantu sources',NULL,NULL,NULL),
(5,1,'Brahmi','Memory and focus','Medhya rasayana references',NULL,NULL,NULL),
(6,1,'Amalaki','Rasayana and immunity','Triphala context',NULL,NULL,NULL),
(7,1,'Shatavari','Female vitality and cooling','Classical rasayana lines',NULL,NULL,NULL),
(8,1,'Guduchi','Fever and immune support','Jwara chikitsa sections',NULL,NULL,NULL),
(9,1,'Shigru','Nutritional support','Regional Ayurvedic practice',NULL,NULL,NULL),
(10,1,'Manjistha','Rakta shodhana','Nighantu literature',NULL,NULL,NULL),
(11,1,'Haritaki','Digestive cleansing','Triphala formulation text',NULL,NULL,NULL),
(12,1,'Yashtimadhu','Throat and respiratory soothing','Kasa references',NULL,NULL,NULL),
(13,1,'Mandukaparni','Mind and skin repair','Medhya herb lists',NULL,NULL,NULL),
(14,1,'Punarnava','Edema and renal support','Mutravaha references',NULL,NULL,NULL),
(15,1,'Vidanga','Gut support','Krimighna references',NULL,NULL,NULL),
(16,3,'Ajwain','Digestive correction','Unani pharmacopeial notes','Hot dry',NULL,NULL),
(17,3,'Habbatus Sauda','Metabolic and immune support','Classical Unani use','Hot dry',NULL,NULL),
(18,3,'Arjun','Cardio tonic bark','Unani adaptations','Cold dry',NULL,NULL),
(19,3,'Senna','Bowel regulation','Unani laxative catalog','Hot dry',NULL,NULL),
(20,3,'Atees','Digestive and fever support','Regional Unani records','Cold dry',NULL,NULL),
(21,4,'Nilavembu','Fever protocol herb','Siddha formulations',NULL,'Nilavembu',NULL),
(22,4,'Keezhanelli','Liver support','Siddha clinical traditions',NULL,'Keezhanelli',NULL),
(23,4,'Thoothuvalai','Respiratory support','Siddha respiratory recipes',NULL,'Thoothuvalai',NULL),
(24,4,'Kokilaksha','Urinary support','Siddha urinary formulations',NULL,'Kokilaksha',NULL),
(25,4,'Vembu','Skin and blood support','Siddha materia medica',NULL,'Vembu',NULL),
(26,5,'Arnica','Trauma tendency pattern support','Materia Medica',NULL,NULL,'Mother tincture Q and potencies 30C/200C'),
(27,5,'Belladonna','Acute fever symptom pattern support','Materia Medica',NULL,NULL,'Potencies 30C/200C used by practitioners'),
(28,5,'Calendula','Topical wound support pattern','Materia Medica',NULL,NULL,'Q mother tincture topical and 30C oral pattern use'),
(29,5,'Hypericum','Nerve pain pattern support','Materia Medica',NULL,NULL,'Potencies 30C and 200C under supervision'),
(30,5,'Pulsatilla','Mood and hormonal symptom pattern support','Materia Medica',NULL,NULL,'Potencies 30C/200C based on constitution'),
(31,2,'Shankhpushpi','Focus and sattvic calm support','Yoga wellness references',NULL,NULL,NULL),
(32,2,'Vacha','Speech and clarity support','Yogic memory traditions',NULL,NULL,NULL),
(33,2,'Jatamansi','Meditative calm and sleep support','Yoga-nidra support literature',NULL,NULL,NULL),
(34,2,'Kapikacchu','Vitality and neuromotor support','Yogic strengthening protocols',NULL,NULL,NULL),
(35,2,'Bhringraj','Rejuvenation support for yoga routines','Yoga wellness handbooks',NULL,NULL,NULL),
(1,2,'Tulsi','Breath and pranayama support','Yoga respiratory routines',NULL,NULL,NULL),
(5,2,'Brahmi','Meditation clarity support','Yoga concentration practice notes',NULL,NULL,NULL);

INSERT INTO plant_garden_zones (plant_id, zone_id) VALUES
(1,1),(2,1),(3,1),(4,2),(5,5),(6,2),(7,8),(8,1),(9,8),(10,1),(11,2),(12,3),(13,5),(14,8),(15,1),
(16,4),(17,4),(18,4),(19,4),(20,4),
(21,6),(22,6),(23,6),(24,6),(25,6),
(26,7),(27,7),(28,7),(29,7),(30,7),
(31,5),(32,5),(33,5),(34,5),(35,3);

INSERT INTO plant_ailments (plant_id, ailment_id, how_used, dosage_form, notes) VALUES
(1,3,'Leaf infusion daily','Tea 100 ml','Supports seasonal immunity'),
(1,8,'Warm decoction with ginger','Kadha','Useful in mild congestion'),
(2,5,'Root extract evening','Capsule 300 mg','Stress resilience support'),
(2,9,'With warm milk at night','Powder 3 g','Sleep support'),
(3,7,'With black pepper','Powder 2 g','Inflammation support'),
(3,4,'Topical paste','Paste','Skin glow support'),
(4,4,'Leaf paste external','Topical','Skin care support'),
(4,6,'Leaf/bark decoction supervised','Decoction','Metabolic support'),
(5,12,'Daily standardized extract','Capsule 250 mg','Memory support'),
(6,3,'Fresh fruit or powder','Food form','Rasayana support'),
(8,1,'Stem decoction','Decoction','Fever support'),
(9,3,'Leaf food supplement','Powder','Nutrition and immunity'),
(12,8,'Root decoction','Syrup or tea','Throat soothing'),
(18,15,'Bark decoction supervised','Decoction','Cardiac support'),
(21,1,'Bitter decoction short course','Kashayam','Traditional fever protocol'),
(22,13,'Whole plant decoction','Decoction','Liver support'),
(23,8,'Leaf chutney/soup','Food form','Respiratory support'),
(24,14,'Seed preparation','Powder','Urinary support'),
(31,12,'Herbal syrup','Syrup','Concentration support'),
(35,10,'Herbal oil and internal powder','Oil + powder','Hair vitality support');

INSERT INTO cultivation_info (plant_id, soil_type, ph_min, ph_max, sunlight, water_needs, best_season, propagation_method, growth_duration, companion_plants, grow_at_home_tips) VALUES
(1,'Well-drained loam',6.00,7.50,'FULL_SUN','MODERATE','Spring and monsoon','Seeds and cuttings','90 days','Marigold, lemongrass','Pinch tips weekly for bushy growth'),
(2,'Sandy loam',6.50,8.00,'FULL_SUN','LOW','Late spring','Seeds','150 days','Coriander, cumin','Do not overwater root crops'),
(3,'Rich loam',5.50,7.50,'PARTIAL_SHADE','MODERATE','Monsoon','Rhizome division','240 days','Chili, onion','Mulch heavily during growth'),
(4,'Alluvial',6.20,8.00,'FULL_SUN','LOW','Monsoon','Seeds','2-3 years','Amla, arjun','Prune in late winter'),
(5,'Wet loam',5.50,7.00,'PARTIAL_SHADE','HIGH','Monsoon','Stem cuttings','70 days','Gotu kola','Keep root zone consistently moist'),
(31,'Light loam',6.00,7.50,'FULL_SUN','MODERATE','Spring','Seeds','80 days','Brahmi','Harvest top growth before flowering'),
(35,'Moist loam',6.00,7.20,'FULL_SUN','MODERATE','Monsoon','Seeds','75 days','Amla','Clip flower heads for prolonged leaf growth');

INSERT INTO phytochemistry (plant_id, compound_name, compound_type, key_action, simple_explanation) VALUES
(1,'Eugenol','Phenylpropanoid','Antioxidant and respiratory support','Acts like a natural aromatic protector.'),
(2,'Withanolides','Steroidal lactones','Adaptogenic activity','Helps body adapt to stress.'),
(3,'Curcumin','Polyphenol','Anti-inflammatory support','Supports balanced inflammatory response.'),
(5,'Bacosides','Saponins','Cognitive support','Supports memory and processing.'),
(8,'Tinosporin','Alkaloid blend','Immunomodulation','Helps maintain resilient immune balance.'),
(18,'Arjunolic acid','Triterpenoid','Cardio support','Supports cardiovascular tone.'),
(21,'Andrographolide','Diterpene lactone','Fever and immune support','Very bitter compounds linked to fever support.');

INSERT INTO research_studies (plant_id, title, authors, journal, year, url, abstract_summary) VALUES
(1,'Tulsi and immune modulation: a review','Sharma et al.','Journal of Integrative Health',2021,'https://pubmed.ncbi.nlm.nih.gov/','Tulsi shows potential immune and stress support in preliminary human studies.'),
(2,'Withania somnifera in stress outcomes','Gupta et al.','Phytotherapy Research',2020,'https://pubmed.ncbi.nlm.nih.gov/','Ashwagandha supplementation improved stress markers in controlled trials.'),
(3,'Curcumin and inflammatory pathways','Rao et al.','Nutrients',2022,'https://pubmed.ncbi.nlm.nih.gov/','Curcumin demonstrates broad anti-inflammatory mechanistic evidence.'),
(5,'Bacopa monnieri and cognition','Patel et al.','Evidence-Based Complementary Medicine',2019,'https://pubmed.ncbi.nlm.nih.gov/','Bacopa may improve memory scores in repeated-use protocols.'),
(18,'Terminalia arjuna cardiovascular potential','Iqbal et al.','Cardio Herbal Review',2018,'https://pubmed.ncbi.nlm.nih.gov/','Arjuna bark is associated with supportive outcomes in selected cardiac parameters.');

INSERT INTO remedies (id, name, for_ailment, ailment_id, difficulty, prep_time_minutes, description, precautions, rating_avg, rating_count) VALUES
(1,'Ginger Tulsi Kadha','Fever and Flu',1,'BEGINNER',15,'Warming decoction for early cold signs.','Avoid overuse in high acidity.',4.70,42),
(2,'Turmeric Milk','Better Sleep',9,'BEGINNER',10,'Night tonic for recovery and sleep comfort.','Use low dose in lactose intolerance.',4.60,38),
(3,'Neem Skin Paste','Skin Care',4,'BEGINNER',12,'Topical leaf paste for blemish-prone skin.','Patch test before use.',4.40,25),
(4,'Brahmi Calm Tea','Stress and Anxiety',5,'BEGINNER',8,'Mild calming infusion for focus and calm.','Avoid before driving if drowsy.',4.50,30),
(5,'Giloy Immunity Decoction','Immunity',3,'INTERMEDIATE',20,'Bitter stem decoction for resilience.','Monitor blood glucose.',4.30,27),
(6,'Amla Digestive Tonic','Digestion',2,'BEGINNER',10,'Sour digestive blend for appetite support.','Avoid in severe gastritis.',4.20,21),
(7,'Mulethi Throat Brew','Respiratory',8,'BEGINNER',12,'Sweet root brew for throat comfort.','Not for uncontrolled hypertension.',4.60,33),
(8,'Arjun Heart Decoction','Heart Health',15,'INTERMEDIATE',25,'Bark decoction under practitioner guidance.','Not a substitute for prescribed medicines.',4.10,18),
(9,'Punarnava Kidney Tea','Kidney Support',14,'INTERMEDIATE',18,'Hydrating support blend for urinary comfort.','Use with clinician in kidney disease.',4.20,16),
(10,'Bhringraj Hair Oil','Hair Growth',10,'INTERMEDIATE',30,'Infused oil for scalp nourishment.','Avoid eye contact.',4.80,44),
(11,'Shankhpushpi Brain Syrup','Memory and Focus',12,'BEGINNER',15,'Cognitive support syrup for study routines.','Check sugar content in diabetics.',4.40,26),
(12,'Nilavembu Fever Kashayam','Fever and Flu',1,'INTERMEDIATE',20,'Traditional bitter fever support decoction.','Use short term and supervised.',4.30,29),
(13,'Keezhanelli Liver Decoction','Liver Support',13,'INTERMEDIATE',20,'Liver support decoction from whole plant.','Monitor with liver medications.',4.20,19),
(14,'Ajwain Digestive Water','Digestion',2,'BEGINNER',7,'Carminative water for bloating relief.','Avoid excess in gastritis.',4.50,34),
(15,'Kalonji Honey Mix','Immunity',3,'BEGINNER',5,'Seed powder and honey for seasonal support.','Moderate use in diabetes.',4.30,28),
(16,'Jatamansi Sleep Blend','Better Sleep',9,'INTERMEDIATE',14,'Night blend for deep calming support.','May enhance sedative effects.',4.40,22),
(17,'Gotu Kola Skin Drink','Skin Care',4,'BEGINNER',9,'Hydrating herbal infusion for skin vitality.','Observe for sensitivity.',4.10,15),
(18,'Haritaki Bowel Formula','Digestion',2,'INTERMEDIATE',16,'Traditional nightly bowel support formula.','Do not use in diarrhea.',4.00,14),
(19,'Vacha Voice Support Mix','Throat Support',8,'ADVANCED',12,'Classical voice support blend in tiny doses.','Requires professional dosing.',3.90,9),
(20,'Moringa Nutrition Soup','Immunity',3,'BEGINNER',20,'Leaf-based nutritive soup for daily strength.','Adjust for oxalate sensitivity.',4.70,41);

INSERT INTO remedy_plants (remedy_id, plant_id) VALUES
(1,1),(1,3),(2,3),(3,4),(4,5),(5,8),(6,6),(7,12),(8,18),(9,14),
(10,35),(11,31),(12,21),(13,22),(14,16),(15,17),(16,33),(17,13),(18,11),(19,32),(20,9);

INSERT INTO remedy_ingredients (remedy_id, plant_id, ingredient_name, quantity, notes) VALUES
(1,1,'Tulsi leaves','10 leaves','Fresh preferred'),
(1,NULL,'Ginger','1 inch','Crushed'),
(1,NULL,'Black pepper','4 grains','Lightly crushed'),
(2,3,'Turmeric powder','1/2 tsp','Organic preferred'),
(2,NULL,'Milk','200 ml','Any dairy or plant milk'),
(3,4,'Neem leaves','15 leaves','Washed and ground'),
(4,5,'Brahmi','1 tsp dried','Steep for 5 minutes'),
(5,8,'Giloy stem','8 cm','Boil to half'),
(6,6,'Amla powder','1 tsp','Stir in warm water'),
(7,12,'Mulethi root','3 g','Simmer gently'),
(8,18,'Arjun bark','5 g','Decoct in water'),
(9,14,'Punarnava','4 g','Use supervised'),
(10,35,'Bhringraj','20 g','Infuse in oil'),
(11,31,'Shankhpushpi','5 g','Syrup base'),
(12,21,'Nilavembu','5 g','Traditional kashayam'),
(13,22,'Keezhanelli','6 g','Fresh preferred'),
(14,16,'Ajwain seeds','1 tsp','Boil and strain'),
(15,17,'Kalonji seeds','1/2 tsp','Powdered'),
(16,33,'Jatamansi','2 g','Night use'),
(17,13,'Gotu kola','5 g','Fresh leaves'),
(18,11,'Haritaki powder','1 tsp','At bedtime'),
(19,32,'Vacha powder','pinch','Very low dose'),
(20,9,'Moringa leaves','1 cup','Cook lightly');

INSERT INTO remedy_steps (remedy_id, step_number, instruction) VALUES
(1,1,'Add ingredients to 300 ml water and boil.'),(1,2,'Reduce to 150 ml and strain.'),(1,3,'Serve warm.'),
(2,1,'Warm milk on low flame.'),(2,2,'Add turmeric and stir.'),(2,3,'Serve before bedtime.'),
(3,1,'Grind leaves to fine paste.'),(3,2,'Apply on affected area.'),(3,3,'Rinse after 15 minutes.'),
(4,1,'Boil water and add brahmi.'),(4,2,'Steep for 5 minutes.'),(4,3,'Drink warm.'),
(5,1,'Boil chopped stem in water.'),(5,2,'Reduce to half.'),(5,3,'Take as advised.'),
(6,1,'Mix amla powder in warm water.'),(6,2,'Stir thoroughly.'),(6,3,'Consume after meal.'),
(7,1,'Simmer mulethi in water.'),(7,2,'Strain after 10 minutes.'),(7,3,'Sip warm.'),
(8,1,'Add bark to water and boil.'),(8,2,'Reduce by half.'),(8,3,'Use under supervision.'),
(9,1,'Decoct herb in water.'),(9,2,'Strain and cool.'),(9,3,'Consume with guidance.'),
(10,1,'Heat base oil gently.'),(10,2,'Infuse bhringraj for 20 minutes.'),(10,3,'Cool, strain, and bottle.'),
(11,1,'Prepare decoction of shankhpushpi.'),(11,2,'Blend with syrup base.'),(11,3,'Store refrigerated.'),
(12,1,'Boil nilavembu with water.'),(12,2,'Reduce to one-third.'),(12,3,'Consume short term.'),
(13,1,'Crush fresh keezhanelli.'),(13,2,'Boil and strain.'),(13,3,'Take as prescribed.'),
(14,1,'Boil ajwain in water.'),(14,2,'Strain and cool slightly.'),(14,3,'Sip post meals.'),
(15,1,'Powder kalonji seeds.'),(15,2,'Mix with honey.'),(15,3,'Take in small quantity.'),
(16,1,'Simmer jatamansi gently.'),(16,2,'Strain and serve warm.'),(16,3,'Take at night.'),
(17,1,'Wash gotu kola leaves.'),(17,2,'Steep in warm water.'),(17,3,'Consume fresh.'),
(18,1,'Blend haritaki with warm water.'),(18,2,'Stir until smooth.'),(18,3,'Take before bed if advised.'),
(19,1,'Mix micro-dose vacha with carrier.'),(19,2,'Take only supervised dose.'),(19,3,'Do not exceed recommendation.'),
(20,1,'Saute moringa leaves lightly.'),(20,2,'Simmer in soup base.'),(20,3,'Serve hot.');

INSERT INTO quiz_questions (id, question_text, option_a, dosha_a, option_b, dosha_b, option_c, dosha_c, display_order) VALUES
(1,'Your natural body frame is usually:','Light and lean','VATA','Medium and athletic','PITTA','Broad and sturdy','KAPHA',1),
(2,'Your appetite is generally:','Irregular','VATA','Strong and sharp','PITTA','Steady and moderate','KAPHA',2),
(3,'Your skin tends to be:','Dry and cool','VATA','Warm and sensitive','PITTA','Soft and moist','KAPHA',3),
(4,'Your response under stress is:','Worry and overthinking','VATA','Irritation and impatience','PITTA','Withdrawal and heaviness','KAPHA',4),
(5,'Your sleep pattern is:','Light and interrupted','VATA','Moderate but can be disturbed','PITTA','Deep and prolonged','KAPHA',5),
(6,'Your speech style is:','Fast and variable','VATA','Clear and intense','PITTA','Slow and measured','KAPHA',6),
(7,'Your weather preference is:','Warm and humid','VATA','Cool climate','PITTA','Dry and warm','KAPHA',7),
(8,'Your memory pattern is:','Quick to learn, quick to forget','VATA','Accurate and analytical','PITTA','Slow to learn, long retention','KAPHA',8),
(9,'Your energy through day is:','Comes in bursts','VATA','Strong and focused','PITTA','Steady but can feel sluggish','KAPHA',9),
(10,'Your social tendency is:','Talkative and enthusiastic','VATA','Goal-oriented and assertive','PITTA','Calm and supportive','KAPHA',10);

-- Plant identification quiz support is intentionally represented via application logic
-- using random plant records from plants table (no separate table in schema).
