export const FALLBACK_REMEDIES = [
  {
    id: 'fr1',
    name: 'Tulsi Ginger Immunity Tea',
    difficulty: 'BEGINNER',
    forAilment: 'Immunity & Cold',
    description: 'A time-tested preparation combining the antimicrobial properties of Tulsi with the warming effect of Ginger.',
    prepTimeMinutes: 10,
    ratingAvg: 4.7,
    ratingCount: 128,
  },
  {
    id: 'fr2',
    name: 'Triphala Digestive Tonic',
    difficulty: 'BEGINNER',
    forAilment: 'Digestion',
    description: 'The classic Ayurvedic three-fruit formula for gentle detox and improved gut health.',
    prepTimeMinutes: 5,
    ratingAvg: 4.5,
    ratingCount: 95,
  },
  {
    id: 'fr3',
    name: 'Ashwagandha Warm Milk',
    difficulty: 'BEGINNER',
    forAilment: 'Stress & Sleep',
    description: 'Traditional adaptogen preparation with ashwagandha root powder in warm milk to promote deep sleep.',
    prepTimeMinutes: 8,
    ratingAvg: 4.6,
    ratingCount: 87,
  },
  {
    id: 'fr4',
    name: 'Turmeric Golden Paste',
    difficulty: 'INTERMEDIATE',
    forAilment: 'Joint Pain & Inflammation',
    description: 'Potent anti-inflammatory blend of turmeric, black pepper, and coconut oil for joint support.',
    prepTimeMinutes: 20,
    ratingAvg: 4.4,
    ratingCount: 74,
  },
  {
    id: 'fr5',
    name: 'Brahmi Memory Infusion',
    difficulty: 'BEGINNER',
    forAilment: 'Memory & Focus',
    description: 'A classical Brahmi preparation to support cognitive clarity and reduce mental fatigue.',
    prepTimeMinutes: 12,
    ratingAvg: 4.3,
    ratingCount: 62,
  },
  {
    id: 'fr6',
    name: 'Neem Skin Decoction',
    difficulty: 'INTERMEDIATE',
    forAilment: 'Skin Care',
    description: 'A purifying Neem leaf decoction applied externally to address skin inflammation and infections.',
    prepTimeMinutes: 25,
    ratingAvg: 4.2,
    ratingCount: 53,
  },
  {
    id: 'fr7',
    name: 'Amla Vitamin C Shot',
    difficulty: 'BEGINNER',
    forAilment: 'Immunity & Hair',
    description: 'Fresh Amla juice preparation packed with natural Vitamin C for immunity and hair strength.',
    prepTimeMinutes: 5,
    ratingAvg: 4.8,
    ratingCount: 141,
  },
  {
    id: 'fr8',
    name: 'Guduchi Fever Decoction',
    difficulty: 'INTERMEDIATE',
    forAilment: 'Fever & Infection',
    description: 'Traditional Guduchi stem decoction used in fever management and immune restoration.',
    prepTimeMinutes: 30,
    ratingAvg: 4.1,
    ratingCount: 39,
  },
  {
    id: 'fr9',
    name: 'Bhringraj Hair Oil',
    difficulty: 'ADVANCED',
    forAilment: 'Hair Loss',
    description: 'Oil infusion of Bhringraj leaves in sesame oil for scalp nourishment and hair growth.',
    prepTimeMinutes: 45,
    ratingAvg: 4.6,
    ratingCount: 112,
  },
  {
    id: 'fr10',
    name: 'Licorice Throat Soothe',
    difficulty: 'BEGINNER',
    forAilment: 'Sore Throat',
    description: 'Gentle Licorice root infusion to coat and soothe inflamed throat tissue.',
    prepTimeMinutes: 8,
    ratingAvg: 4.4,
    ratingCount: 67,
  },
  {
    id: 'fr11',
    name: 'Trikatu Digestive Stimulant',
    difficulty: 'INTERMEDIATE',
    forAilment: 'Slow Digestion',
    description: 'The three-pepper classical formula combining Ginger, Black Pepper, and Long Pepper.',
    prepTimeMinutes: 5,
    ratingAvg: 4.0,
    ratingCount: 44,
  },
  {
    id: 'fr12',
    name: 'Brahmi Ghrita Brain Tonic',
    difficulty: 'ADVANCED',
    forAilment: 'Cognitive Health',
    description: 'Ghee-based classical preparation with Brahmi and Shankhpushpi for cognitive enhancement.',
    prepTimeMinutes: 60,
    ratingAvg: 4.7,
    ratingCount: 33,
  },
];
